[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../third_party/rust_crates/vendor"

[build]
target-dir = "../out/cargo_target"
rustflags = ["-Wrust-2018-idioms"]

[env]
# We need to override this environment variable for `include_bytes_from_working_dir`. However, this
# won't be the right setting for users who fx set with `--dir` or `--auto-dir`. In that case, users
# should manually set the FUCHSIA_BUILD_DIR environment variable via .bashrc. This config will only
# set the variable if it's not already present.
FUCHSIA_BUILD_DIR = { value = "../out/default", relative = true }

# Override these crates' build scripts, and instead link to our existing versions of the native
# libraries.
# See https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts.

[target.x86_64-unknown-fuchsia.ring_core_0_17_8]
rustc-env = { RING_CORE_PREFIX = "ring_core_0_17_8_" }

[target.x86_64-unknown-linux-gnu.ring_core_0_17_8]
rustc-env = { RING_CORE_PREFIX = "ring_core_0_17_8_" }

[target.x86_64-apple-darwin.ring_core_0_17_8]
rustc-env = { RING_CORE_PREFIX = "ring_core_0_17_8_" }
